name: Node.js CI

on:
  push:
    branches: [ "master" ] # Запускать при пуше в main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Укажи свою версию ноды
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      env:
        # Указываем заглушки для билда, чтобы Next.js не ругался на отсутствие переменных
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
